wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1710077847
    t:
      1:
      - 1
      - 9
      - 41
      - 48
      - 50
      - 55
      2:
      - 1
      - 9
      - 41
      - 48
      - 50
      - 55
      3:
      - 1
      4: 3.8.18
      5: 0.12.21
      8:
      - 3
      - 5
